import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from 'next/font/local'
import NextAuthProvider from "@/provider/NextAuthProvider";


const poppins = Poppins({
  weight:["100","200","400","500","600","800"]
});

export const fontBangla = localFont({
  src: "./../fonts/mayaboti-normal.ttf",
});

// export const metadata = {
//   title: {
//     default:"Hero Kidz",
//     template:"%s | Hero Kidz",
//   },
//   description: "Generated by create next app",
// };

export const metadata = {
  metadataBase: new URL("https://hero-kidz-lake.vercel.app"),

  title: {
    default: "Hero Kidz | Educational Toys for Kids",
    template: "%s | Hero Kidz",
  },

  description:
    "Hero Kidz offers educational and engaging toys for children, designed to make learning fun, interactive, and enjoyable.",

  keywords: [
    "Hero Kidz",
    "educational toys",
    "kids toys",
    "learning toys",
    "children toys",
    "educational toys Bangladesh",
  ],

  applicationName: "Hero Kidz",
  authors: [{ name: "Hero Kidz" }],
  creator: "Hero Kidz",
  publisher: "Hero Kidz",

  alternates: {
    canonical: "/",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Hero Kidz",
    title: "Hero Kidz | Educational Toys for Kids",
    description:
      "Discover educational and engaging toys for children at Hero Kidz. Make learning fun, interactive, and enjoyable.",
    url: "/",
    images: [
      {
        url: "/assets/hero.png",
        width: 1200,
        height: 630,
        alt: "Hero Kidz - Educational Toys for Kids",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Hero Kidz | Educational Toys for Kids",
    description:
      "Discover educational and engaging toys for children at Hero Kidz.",
    images: ["/assets/hero.png"],
  },

  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
    <html
      lang="en"
    >
      <body className={`${poppins.className} h-full antialiased`}>
      <header className="py-2 md:w-11/12 mx-auto">
      <Navbar></Navbar>  
      </header>  
      <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100svh-302px)]">
          {children}
      </main>
      <footer>
      <Footer></Footer>
      </footer>
      </body>
    </html>
    </NextAuthProvider>
  );
}
